// Run against the local dev server. Screenshots are taken separately with Oil UI shoot.
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.UI_BASE_URL || 'http://127.0.0.1:4328';
const url = `${base}/?${new URLSearchParams({ cwd: process.cwd() })}`;
const browser = await chromium.launch({ channel: 'chrome', headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1600, height: 1000 }, permissions: ['clipboard-read','clipboard-write'] });
  const page = await context.newPage(), errors = [], writes = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', req => { if (req.url().includes('/api/') && req.method() !== 'GET') writes.push(req.method()); });
  page.setDefaultTimeout(15000);
  const loaded = () => page.locator('.details .patch .line').first().waitFor();
  const theme = async value => { await page.waitForFunction(v => document.documentElement.dataset.theme === v, value); };
  await page.goto(url); await loaded();
  await theme('light');
  assert.equal(await page.locator('.toolbar').evaluate(el => el.getBoundingClientRect().height), 60);
  assert.equal(await page.locator('.sidebar').evaluate(el => el.getBoundingClientRect().width), 250);
  assert.equal(await page.locator('.log').evaluate(el => el.getBoundingClientRect().width), 430);
  await page.locator('.file-menu summary').click();
  await page.locator('.file-menu-list button[title="codex/plugin.json"]').click(); await loaded();
  assert.match(await page.locator('.patch').innerText(), /mogoo-codex-git/);
  await page.getByRole('button', { name:'复制完整提交哈希' }).click();
  assert.match(await page.evaluate(() => navigator.clipboard.readText()), /^[a-f0-9]{40,64}$/);
  const query = page.getByRole('textbox', { name:'搜索已加载提交' });
  await query.fill('no-such-commit-xyz');
  assert.match(await page.locator('.search-result').innerText(), /^0 个匹配/);
  await page.getByRole('button', {name:'清除搜索'}).click();
  await page.getByRole('combobox', {name:'提交范围'}).click();
  await page.getByRole('option', {name:'master',exact:true}).click(); await loaded();
  await page.locator('.commit').last().click(); await loaded();
  assert.match(await page.locator('.detail-heading').innerText(), /Initial commit/);
  await page.locator('.theme-dark').click(); await theme('dark');
  await page.reload(); await loaded(); await theme('dark');
  await page.getByRole('button', {name:'工作树', exact:true}).click();
  assert.match(await page.locator('.worktree-table').innerText(), /当前聊天/);
  await page.getByRole('button', {name:'改动', exact:true}).click();
  await page.locator('.changes-view .patch .line').first().waitFor();
  await page.setViewportSize({width:760,height:1000});
  assert.equal(await page.locator('.sidebar').isVisible(), false);
  await page.getByRole('combobox', {name:'改动范围'}).selectOption('untracked');
  await page.locator('.changes-view .patch').waitFor();
  await page.getByRole('button', {name:'历史',exact:true}).click(); await loaded();
  assert.equal(await page.locator('.log').evaluate(el => el.getBoundingClientRect().width),230);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
  await page.locator('.theme-light').focus(); await page.keyboard.press('Enter'); await theme('light');
  // A refresh failure preserves selection and keeps the previous repository usable.
  const selected = await page.locator('.commit.active').getAttribute('data-oid');
  await page.route('**/api/context?*', route => route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Temporary read failure'})}));
  await page.getByRole('button', {name:'刷新',exact:true}).click();
  await page.locator('.error-banner').waitFor();
  assert.equal(await page.locator('.commit.active').getAttribute('data-oid'), selected);
  await page.unroute('**/api/context?*');
  await page.getByRole('button', {name:'刷新',exact:true}).click(); await loaded();
  await page.waitForFunction(() => !document.querySelector('.error-banner'));
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
  await context.addInitScript(() => { Storage.prototype.getItem = () => { throw Error('blocked'); }; Storage.prototype.setItem = () => { throw Error('blocked'); }; });
  await page.reload(); await loaded(); await page.locator('.theme-dark').click(); await theme('dark');
  await page.goto(base); await page.getByText('等待当前聊天关联',{exact:true}).waitFor();
  assert.deepEqual(errors, []); assert.deepEqual(writes, []);
  console.log('PASS: real Git data, exact layout dimensions, files, copy, search, refs, commits, worktrees, changes, theme persistence/keyboard/storage failure, refresh recovery, 760/390px, unbound state, read-only requests.');
  await context.close();
} finally { await browser.close(); }
